# Generated by Django 3.1.3 on 2021-01-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
