# Generated by Django 3.1.3 on 2021-01-09 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_haber_ispublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
