# Generated by Django 3.1.3 on 2021-01-13 07:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210110_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Blog Post Adı')),
                ('summary', models.TextField(verbose_name='Blog Post Özeti')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Blog Post Metni')),
                ('image', models.ImageField(max_length=50, upload_to='', verbose_name='Blog Post Resmi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('writername', models.CharField(max_length=50, verbose_name='Yazar Adı')),
                ('theme', models.CharField(max_length=50, verbose_name='Tema Rengi')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
