# Generated by Django 3.1.3 on 2021-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default=0, max_length=50, verbose_name='Blog Post Kategori'),
            preserve_default=False,
        ),
    ]
